name: SkyMansion_Ad_Bot
on:
  schedule:
    - cron: '0 0,12 * * *' # 日本時間の 9:00 と 21:00 に自動実行
  workflow_dispatch: # これを書くと「手動発射ボタン」が出るようになる

jobs:
  run_bot:
    runs-on: ubuntu-latest
    steps:
      - name: コードを取得
        uses: actions/checkout@v4

      - name: Pythonをセットアップ
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 必要な道具（tweepy）をインストール
        run: pip install -r requirements.txt

      - name: スカイマンションの声明を放流
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
        run: python bot.py
